name: Release - Build & Deploy Docker Image

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  docker:
    name: Fetch Github Submodules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          token: ${{ secrets.PAT }}
      - name: Create Semver Tags
        if: startsWith(github.ref, 'refs/tags/v') == true
        run: |
          refVersionIN=${GITHUB_REF##*/}
          refVersionIN=${refVersionIN/v/}
          echo "tag=${refVersionIN}" >> $GITHUB_ENV
      - name: No Semver Tag
        if: startsWith(github.ref, 'refs/tags/v') == false
        run: |
          echo "tag=" >> $GITHUB_ENV
      - name: Build & Deploy
        uses: philips-software/docker-ci-scripts@v4.5.0
        with:
          dockerfile: Dockerfile
          # Todo: Provide a name for the docker image
          image-name: <DOCKER_IMAGE>
          tags: "latest ${{ env.tag }}"
          push-on-git-tag: "true"
        env:
          REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USER }}
          REGISTRY_TOKEN: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
          DOCKER_ORGANIZATION: ${{ secrets.DOCKER_REGISTRY_ORG }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          NG_API_URL: ${{ secrets.NG_API_URL }}
          NG_APP_VERSION: ${{ secrets.NG_APP_VERSION }}
          NG_APP_ENV: ${{ secrets.NG_APP_ENV }}
          NG_APP_NAME: ${{ secrets.NG_APP_NAME }}
          NG_APP_LANG: ${{ secrets.NG_APP_LANG }}
          NG_APP_LOGO: ${{ secrets.NG_APP_LOGO }}
          DOCKER_BUILD_ARGS: "--build-arg NG_AUTH_URL --build-arg NG_APP_VERSION --build-arg NG_API_URL --build-arg NODE_AUTH_TOKEN --build-arg NG_APP_ENV --build-arg NG_APP_NAME --build-arg NG_APP_LANG --build-arg NG_APP_LOGO"

  deploy:
    name: Deploy Web App using webhooks
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.PROD_WEBHOOKS_URL }}
        env:
          WEBHOOK_URL: ${{ secrets.PROD_WEBHOOKS_URL  }}
